CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL UNIQUE,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    name TEXT NOT NULL,
    CONSTRAINT categories_user_id_name_key UNIQUE (user_id, name),
    CONSTRAINT categories_user_id_id_key UNIQUE (user_id, id)
);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    category_id BIGINT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
    currency VARCHAR(3) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    spent_at TIMESTAMPTZ NOT NULL,
    source_update_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT expenses_user_category_fkey
        FOREIGN KEY (user_id, category_id) REFERENCES categories (user_id, id)
);

CREATE INDEX expenses_user_id_spent_at_idx ON expenses (user_id, spent_at DESC);
